Repository teamterning/Terning-Android, pull requests merged in 2024-07, with the labels that each got.

#7 [ADD/#6] Design System 기초세팅
  core/src/main/java/com/terning/core/designsystem/theme/Color.kt
  core/src/main/java/com/terning/core/designsystem/theme/Theme.kt
  core/src/main/java/com/terning/core/designsystem/theme/Type.kt
  core/src/main/java/com/terning/core/ui/theme/Color.kt
  core/src/main/java/com/terning/core/ui/theme/Theme.kt
  core/src/main/java/com/terning/core/ui/theme/Type.kt
  core/src/main/res/font/pretendard_light.otf
  core/src/main/res/font/pretendard_medium.otf
  core/src/main/res/font/pretendard_regular.otf
  core/src/main/res/font/pretendard_semibold.otf
  feature/src/main/java/com/terning/feature/main/MainActivity.kt
Labels: ADD ➕, 효빈💚

#10 [ADD/#8] 바텀 네비게이션 추가
  feature/src/main/java/com/terning/feature/calendar/CalendarRouth.kt
  feature/src/main/java/com/terning/feature/calendar/navigation/CalendarNavigation.kt
  feature/src/main/java/com/terning/feature/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/navigation/HometNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/main/MainTab.kt
  feature/src/main/java/com/terning/feature/mypage/MockItem.kt
  feature/src/main/java/com/terning/feature/mypage/MockSideEffect.kt
  feature/src/main/java/com/terning/feature/mypage/MockState.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/navigation/MyPageNavigation.kt
  feature/src/main/java/com/terning/feature/search/SearchRouth.kt
  feature/src/main/java/com/terning/feature/search/navigation/SearchNavigation.kt
  feature/src/main/res/drawable/ic_nav_calendar.xml
  feature/src/main/res/drawable/ic_nav_home.xml
  feature/src/main/res/drawable/ic_nav_my_page.xml
  feature/src/main/res/drawable/ic_nav_search.xml
  feature/src/main/res/values/strings.xml
Labels: ADD ➕, FEAT ✨, 아린💛

#13 [FEAT/#5] 온보딩 뷰 / 카카오 연결
  app/build.gradle.kts
  app/src/main/java/com/terning/point/MyApp.kt
  core/src/main/java/com/terning/core/extension/ContextExt.kt
  feature/build.gradle.kts
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/navigation/FilteringNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInSideEffect.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInState.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/component/KakaoButton.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/navigation/SignInNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/navigation/SignUpNavigation.kt
  feature/src/main/res/drawable/ic_signin_kakao.xml
  feature/src/main/res/drawable/img_terning_point.png
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEAT ✨, 유빈💙

#17 [ADD/#15] TopAppBar
  core/src/main/java/com/terning/core/designsystem/topappbar/BackButtonTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/topappbar/LogoTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/topappbar/MyPageTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/topappbar/TerningTopAppBar.kt
  core/src/main/res/drawable/ic_back.xml
  core/src/main/res/drawable/ic_logo.xml
  core/src/main/res/drawable/ic_right.xml
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/SearchRouth.kt
Labels: ADD ➕, FEAT ✨, 아린💛

#18 [UI/#9] 월간 캘린더 화면
  core/src/main/java/com/terning/core/extension/LocalDateExt.kt
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/calendar/CalendarDay.kt
  feature/src/main/java/com/terning/feature/calendar/CalendarMonth.kt
  feature/src/main/java/com/terning/feature/calendar/CalendarMonths.kt
  feature/src/main/java/com/terning/feature/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/CalendarRouth.kt
  feature/src/main/java/com/terning/feature/calendar/CalendarScrap.kt
  feature/src/main/java/com/terning/feature/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/component/CalendarTopBar.kt
  feature/src/main/java/com/terning/feature/calendar/component/WeekDaysHeader.kt
  feature/src/main/java/com/terning/feature/calendar/models/CalendarDefault.kt
  feature/src/main/java/com/terning/feature/calendar/models/CalendarState.kt
  feature/src/main/java/com/terning/feature/calendar/models/DayModel.kt
  feature/src/main/java/com/terning/feature/calendar/models/MonthData.kt
  feature/src/main/java/com/terning/feature/calendar/models/MonthModel.kt
  feature/src/main/java/com/terning/feature/calendar/models/Scrap.kt
  feature/src/main/res/drawable/ic_calendar_list_selected.xml
  feature/src/main/res/drawable/ic_calendar_list_unselected.xml
  feature/src/main/res/drawable/ic_calendar_next.xml
  feature/src/main/res/drawable/ic_calendar_previous.xml
  feature/src/main/res/drawable/ic_nav_home.xml
  feature/src/main/res/values/strings.xml
Labels: FEAT ✨, UI 💐, 석준💜

#24 [FEAT/#23] 포커스 여부에 따라 힌트 텍스트 색상 변경
  core/src/main/java/com/terning/core/designsystem/textfield/TerningBasicTextField.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
Labels: UI 💐, 아린💛

#21 [ADD/#16] Button / 컴포넌트 구현
  core/build.gradle.kts
  core/src/main/java/com/terning/core/designsystem/component/button/RectangleButton.kt
  core/src/main/java/com/terning/core/designsystem/component/button/RoundButton.kt
  core/src/main/java/com/terning/core/designsystem/component/button/TerningBasicButton.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/BackButtonTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/LogoTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/MyPageTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/textfield/SearchTextField.kt
  core/src/main/java/com/terning/core/designsystem/theme/Color.kt
  core/src/main/java/com/terning/core/designsystem/theme/Theme.kt
  core/src/main/java/com/terning/core/designsystem/theme/Type.kt
  core/src/main/java/com/terning/core/extension/Retrofit.kt
  core/src/main/java/com/terning/core/util/NoRippleInteractionSource.kt
  core/src/main/java/com/terning/core/util/NoRippleTheme.kt
  core/src/main/res/values/strings.xml
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/calendar/CalendarDay.kt
  feature/src/main/java/com/terning/feature/calendar/CalendarMonth.kt
  feature/src/main/java/com/terning/feature/calendar/component/CalendarTopBar.kt
  feature/src/main/java/com/terning/feature/calendar/component/WeekDaysHeader.kt
  feature/src/main/java/com/terning/feature/main/MainActivity.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/component/KakaoButton.kt
  feature/src/main/java/com/terning/feature/search/SearchRoute.kt
  gradle/libs.versions.toml
  project.dot.png
Labels: ADD ➕, 유빈💙

#26 [FIX/#25] develop 브렌치 / 주석 및 컴포넌트 수정
  core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/SearchTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  core/src/main/java/com/terning/core/designsystem/textfield/SearchTextField.kt
  feature/src/main/java/com/terning/feature/search/SearchRoute.kt
Labels: FIX 🔨, 유빈💙

#36 [ADD/#35] Color 속성 추가
  core/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/theme/Color.kt
  core/src/main/java/com/terning/core/designsystem/theme/Theme.kt
Labels: ADD ➕, 유빈💙

#34 [ADD/#27] BottomSheet / 컴포넌트 구현
  core/build.gradle.kts
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/TerningBasicBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/button/TerningBasicButton.kt
  data/src/main/java/com/terning/data/dto/BaseResponse.kt
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpBottomSheet.kt
  feature/src/main/res/drawable/ic_character1.xml
  feature/src/main/res/drawable/ic_character2.xml
  feature/src/main/res/drawable/ic_character3.xml
  feature/src/main/res/drawable/ic_character4.xml
  feature/src/main/res/drawable/ic_character5.xml
  feature/src/main/res/drawable/ic_character6.xml
  feature/src/main/res/drawable/ic_selected_character.xml
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ADD ➕, 유빈💙

#30 [UI/#11] 탐색 뷰 / 탐색 기본 화면 구현
  core/src/main/java/com/terning/core/designsystem/component/textfield/SearchTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/component/DotsIndicator.kt
  feature/src/main/java/com/terning/feature/search/component/ImageSlider.kt
  feature/src/main/java/com/terning/feature/search/component/IndicatorDots.kt
  feature/src/main/java/com/terning/feature/search/component/InternListType.kt
  feature/src/main/java/com/terning/feature/search/component/SearchIntern.kt
  feature/src/main/java/com/terning/feature/search/component/SearchInternList.kt
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 아린💛

#39 [ADD/#38] ScrapBox 컴포넌트 구현
  core/src/main/java/com/terning/core/designsystem/component/box/ScrapBox.kt
Labels: ADD ➕, UI 💐, 석준💜

#45 [ADD/#32] 공고 정렬 바텀시트 구현
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SortBy.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SortingBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/TerningBasicBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/button/SortingButton.kt
  core/src/main/res/drawable/ic_down.xml
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpBottomSheet.kt
Labels: ADD ➕, 효빈💚

#46 [UI/#14] 회원가입 뷰 / UI 구현
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SignUpBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/button/TerningBasicButton.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/SearchTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
  core/src/main/res/drawable/ic_character1.xml
  core/src/main/res/drawable/ic_character2.xml
  core/src/main/res/drawable/ic_character3.xml
  core/src/main/res/drawable/ic_character4.xml
  core/src/main/res/drawable/ic_character5.xml
  core/src/main/res/drawable/ic_character6.xml
  core/src/main/res/drawable/ic_selected_character.xml
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/navigation/FilteringNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/navigation/SignInNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpState.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpProfile.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/navigation/SignUpNavigation.kt
  feature/src/main/res/drawable/ic_check.xml
  feature/src/main/res/drawable/ic_sign_up_button.xml
  feature/src/main/res/drawable/ic_sign_up_error.xml
  feature/src/main/res/drawable/ic_sign_up_profile.xml
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 유빈💙

#47 [UI/#12] 홈뷰 / 홈 기본 화면 구현
  feature/src/main/java/com/terning/feature/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/TerningPostItem.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeFilteringScreen.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendEmptyIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayEmptyIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternItem.kt
  feature/src/main/java/com/terning/feature/home/home/navigation/HometNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/main/MainTab.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/res/drawable/ic_empty_logo.xml
  feature/src/main/res/drawable/ic_home_bookmark_28.xml
  feature/src/main/res/drawable/ic_home_filtering_28.xml
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 효빈💚

#50 [ADD/#49] 필터링 재설정 / Text 컴포넌트 구현
  feature/src/main/java/com/terning/feature/home/changefilter/component/FilteringMainTitleText.kt
  feature/src/main/java/com/terning/feature/home/changefilter/component/FilteringSubTitleText.kt
  feature/src/main/res/values/strings.xml
Labels: ADD ➕, 효빈💚

#54 [UI/#37] 캘린더뷰 / 스크랩 목록 뷰
  core/build.gradle.kts
  core/src/main/java/com/terning/core/designsystem/component/item/InternItem.kt
  core/src/main/java/com/terning/core/designsystem/component/item/ScrapBox.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/CalendarTopAppBar.kt
  core/src/main/java/com/terning/core/extension/LocalDateExt.kt
  core/src/main/res/drawable/ic_bookmark_filled.xml
  core/src/main/res/drawable/ic_bookmark_outlined.xml
  core/src/main/res/drawable/ic_calendar_list_selected.xml
  core/src/main/res/drawable/ic_calendar_list_unselected.xml
  core/src/main/res/drawable/ic_calendar_next.xml
  core/src/main/res/drawable/ic_calendar_previous.xml
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarDay.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarMonth.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarMonths.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarWeek.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarWeekWithScrap.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/WeekDaysHeader.kt
  feature/src/main/java/com/terning/feature/calendar/models/Scrap.kt
  feature/src/main/java/com/terning/feature/calendar/navigation/CalendarNavigation.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrap.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrapListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrapStrip.kt
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: FEAT ✨, UI 💐, 석준💜

#56 [UI/#52] 홈 뷰 / 컴포넌트 적용
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternItem.kt
Labels: UI 💐, 효빈💚

#61 [UI/#53] TerningBasicDialog
  core/src/main/java/com/terning/core/designsystem/component/button/SortingButton.kt
  core/src/main/java/com/terning/core/designsystem/component/dialog/ScrapDialogContent.kt
  core/src/main/java/com/terning/core/designsystem/component/dialog/TerningBasicDialog.kt
  core/src/main/java/com/terning/core/designsystem/component/item/ColorPalette.kt
  core/src/main/java/com/terning/core/designsystem/theme/Color.kt
  core/src/main/res/drawable/ic_dialog_x_32.xml
  core/src/main/res/drawable/ic_down_18.xml
  core/src/main/res/drawable/ic_down_22.xml
  core/src/main/res/drawable/ic_up_22.xml
  core/src/main/res/values/strings.xml
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
Labels: UI 💐, 아린💛

#65 [FIX/#62] 인턴 공고 컴포넌트
  core/src/main/java/com/terning/core/designsystem/component/item/InternItem.kt
  core/src/main/java/com/terning/core/designsystem/component/item/ScrapBox.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrap.kt
Labels: FIX 🔨, 석준💜

#67 [HOTFIX/#66] 인덱싱 오류 수정
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrapListScreen.kt
Labels: HOTFIX 🚑️, 석준💜

#63 [UI/#42] 공고 뷰 / 공고 상세 페이지 구현
  core/src/main/java/com/terning/core/designsystem/component/dialog/ScrapDialogContent.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/BackButtonTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/intern/component/InternBottomBar.kt
  feature/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
  feature/src/main/java/com/terning/feature/intern/component/InternInfoRow.kt
  feature/src/main/java/com/terning/feature/intern/component/InternPageTitle.kt
  feature/src/main/java/com/terning/feature/intern/navigation/InternNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/main/MainTab.kt
  feature/src/main/res/drawable/ic_first_info_20.xml
  feature/src/main/res/drawable/ic_intern_share_22.xml
  feature/src/main/res/drawable/ic_scrap_false_24.xml
  feature/src/main/res/drawable/ic_scrap_true_24.xml
  feature/src/main/res/drawable/ic_second_info_20.xml
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 아린💛

#68 [UI/#60] 홈 뷰 / 홈 뷰 기본 UI 로직 구현
  core/src/main/java/com/terning/core/designsystem/component/item/ScrapBox.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeFilteringEmptyIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
  feature/src/main/java/com/terning/feature/home/home/model/InternFilterData.kt
  feature/src/main/java/com/terning/feature/home/home/model/RecommendInternData.kt
  feature/src/main/java/com/terning/feature/home/home/model/ScrapData.kt
  feature/src/main/java/com/terning/feature/home/home/model/UserNameState.kt
  feature/src/main/java/com/terning/feature/home/home/model/UserScrapState.kt
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 효빈💚

#70 [UI/#48] 온보딩 뷰 / UI 구현
  core/build.gradle.kts
  core/src/main/java/com/terning/core/designsystem/component/button/FilteringButton.kt
  core/src/main/java/com/terning/core/designsystem/component/datepicker/DatePicker.kt
  core/src/main/java/com/terning/core/designsystem/component/image/TerningImage.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/BackButtonTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/theme/Type.kt
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringOneScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringThreeScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringTwoScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/component/StatusOneRadioGroup.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/component/StatusTwoRadioGroup.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/navigation/FilteringOneNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/navigation/FilteringTwoNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/navigation/ThreeNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/startfiltering/StartFilteringScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/startfiltering/navigation/StartFilteringNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/starthome/StartHomeScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/starthome/navigation/StartHomeNavigation.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/res/drawable/ic_filtering_status1.xml
  feature/src/main/res/drawable/ic_filtering_status2.xml
  feature/src/main/res/drawable/ic_filtering_status3.xml
  feature/src/main/res/drawable/img_start.png
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 유빈💙

#74 [UI/#64] 스크랩 취소 다이얼로그 및 말줄임 구현
  core/src/main/java/com/terning/core/designsystem/component/dialog/ScrapDialogContent.kt
  core/src/main/java/com/terning/core/designsystem/component/dialog/TerningBasicDialog.kt
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/src/main/java/com/terning/feature/intern/component/InternBottomBar.kt
  feature/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
  feature/src/main/java/com/terning/feature/intern/component/ScrapCancelDialog.kt
  feature/src/main/java/com/terning/feature/intern/component/ScrapDialogContent.kt
  feature/src/main/java/com/terning/feature/intern/model/InternScrapState.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 아린💛

#75 [FIX/#73] 라이팅 수정
  core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpState.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/res/values/strings.xml
Labels: FIX 🔨, REFACTOR ♻️, 아린💛

#78 [UI/#71] 마이페이지 뷰 / UI 구현
  app/src/main/AndroidManifest.xml
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  feature/src/main/ic_terning_launcher-playstore.png
  feature/src/main/java/com/terning/feature/mypage/MockItem.kt
  feature/src/main/java/com/terning/feature/mypage/MockSideEffect.kt
  feature/src/main/java/com/terning/feature/mypage/MockState.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/component/MyPageItem.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringThreeScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/FilteringTwoScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/filtering/component/StatusTwoRadioGroup.kt
  feature/src/main/res/drawable/ic_filtering_status1.xml
  feature/src/main/res/drawable/ic_filtering_status2.xml
  feature/src/main/res/drawable/ic_filtering_status3.xml
  feature/src/main/res/drawable/ic_my_page.xml
  feature/src/main/res/drawable/ic_my_page_divider.xml
  feature/src/main/res/drawable/ic_my_page_go.xml
  feature/src/main/res/drawable/ic_terning_launcher_background.xml
  feature/src/main/res/mipmap-anydpi-v26/ic_terning_launcher.xml
  feature/src/main/res/mipmap-anydpi-v26/ic_terning_launcher_round.xml
  feature/src/main/res/mipmap-hdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-hdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-hdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-mdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-mdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-mdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-xhdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-xhdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-xhdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-xxhdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-xxhdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-xxhdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-xxxhdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-xxxhdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-xxxhdpi/ic_terning_launcher_round.webp
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 유빈💙

#83 [FIX/#82] Manifest 수정
  app/src/main/AndroidManifest.xml
  feature/src/main/AndroidManifest.xml
Labels: FIX 🔨, 유빈💙

#76 [UI/#51] 필터링 재설정 UI 구현
  core/src/main/java/com/terning/core/designsystem/component/button/ChangeFilterButton.kt
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/changefilter/component/ChangeFilteringRadioGroup.kt
  feature/src/main/java/com/terning/feature/home/changefilter/navigation/ChangeFilterNavigation.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeFilteringScreen.kt
  feature/src/main/java/com/terning/feature/home/home/model/InternFilterData.kt
  feature/src/main/java/com/terning/feature/home/home/navigation/HometNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 효빈💚

#81 [UI/#80] 탐색 뷰 / 공고 컴포넌트 추가
  core/src/main/java/com/terning/core/designsystem/component/item/InternItemWithShadow.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/model/InternData.kt
  feature/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
  feature/src/main/res/drawable/ic_nosearch.xml
Labels: UI 💐, 아린💛

#89 [Feat/#79] 탐색 기본 뷰 / 조회수 많은 공고 통신
  app/src/main/java/com/terning/point/di/DataSourceModule.kt
  app/src/main/java/com/terning/point/di/RepositoryModule.kt
  app/src/main/java/com/terning/point/di/ServiceModule.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  data/src/main/java/com/terning/data/datasource/SearchDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/SearchDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/SearchViewsResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/SearchViewsRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/SearchService.kt
  domain/src/main/java/com/terning/domain/entity/response/InternshipAnnouncement.kt
  domain/src/main/java/com/terning/domain/repository/SearchRepository.kt
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/search/SearchViewModel.kt
  feature/src/main/java/com/terning/feature/search/search/SearchViewsSideEffect.kt
  feature/src/main/java/com/terning/feature/search/search/SearchViewsState.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchIntern.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchInternList.kt
  feature/src/main/res/values/strings.xml
Labels: FEAT ✨, 아린💛

#87 [FEAT/#72] 소셜 로그인 / 서버통신 로직 구현
  app/src/main/java/com/terning/point/di/DataSourceModule.kt
  app/src/main/java/com/terning/point/di/DataStoreModule.kt
  app/src/main/java/com/terning/point/di/RepositoryModule.kt
  app/src/main/java/com/terning/point/di/RetrofitModule.kt
  app/src/main/java/com/terning/point/di/ServiceModule.kt
  app/src/main/java/com/terning/point/di/qualifier/RetrofitQualifier.kt
  data/src/main/java/com/terning/data/datasource/AuthDataSource.kt
  data/src/main/java/com/terning/data/datasource/MockDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/AuthDataSourceImpl.kt
  data/src/main/java/com/terning/data/datasourceimpl/MockDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/NonDataBaseResponse.kt
  data/src/main/java/com/terning/data/dto/request/SignInRequestDto.kt
  data/src/main/java/com/terning/data/dto/response/MockResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/SignInResponseDto.kt
  data/src/main/java/com/terning/data/local/TerningDataStore.kt
  data/src/main/java/com/terning/data/local/TerningDataStoreImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/AuthRepositoryImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/MockRepositoryImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/TokenRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/AuthService.kt
  data/src/main/java/com/terning/data/service/MockService.kt
  domain/src/main/java/com/terning/domain/entity/request/SignInRequestModel.kt
  domain/src/main/java/com/terning/domain/entity/response/MockResponseModel.kt
  domain/src/main/java/com/terning/domain/entity/response/SignInResponseModel.kt
  domain/src/main/java/com/terning/domain/repository/AuthRepository.kt
  domain/src/main/java/com/terning/domain/repository/MockRepository.kt
  domain/src/main/java/com/terning/domain/repository/TokenRepository.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInSideEffect.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/src/main/res/values/strings.xml
Labels: FEAT ✨, 유빈💙

#102 [FEAT/#96] 토큰 재발급 / 서버통신 구현
  app/build.gradle.kts
  app/src/main/java/com/terning/point/di/AuthInterceptor.kt
  app/src/main/java/com/terning/point/di/DataSourceModule.kt
  app/src/main/java/com/terning/point/di/RepositoryModule.kt
  app/src/main/java/com/terning/point/di/RetrofitModule.kt
  app/src/main/java/com/terning/point/di/ServiceModule.kt
  app/src/main/java/com/terning/point/di/qualifier/RetrofitQualifier.kt
  core/src/main/java/com/terning/core/extension/ContextExt.kt
  data/src/main/java/com/terning/data/datasource/TokenReissueDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/TokenReissueDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/TokenReissueResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/TokenReissueRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/TokenReissueService.kt
  domain/src/main/java/com/terning/domain/entity/response/TokenReissueResponseModel.kt
  domain/src/main/java/com/terning/domain/repository/TokenReissueRepository.kt
  gradle/libs.versions.toml
Labels: FEAT ✨, 유빈💙

#90 [FEAT/#59] 캘린더뷰 / 월간 캘린더 서버통신 로직 구현
  app/src/main/java/com/terning/point/di/DataSourceModule.kt
  app/src/main/java/com/terning/point/di/RepositoryModule.kt
  app/src/main/java/com/terning/point/di/ServiceModule.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/CalendarTopAppBar.kt
  core/src/main/java/com/terning/core/extension/LocalDateExt.kt
  core/src/main/java/com/terning/core/extension/Map.kt
  data/src/main/java/com/terning/data/datasource/CalendarDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/CalendarDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/request/CalendarDayListRequestDto.kt
  data/src/main/java/com/terning/data/dto/request/CalendarMonthListRequestDto.kt
  data/src/main/java/com/terning/data/dto/request/CalendarMonthRequestDto.kt
  data/src/main/java/com/terning/data/dto/response/CalendarDayListResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/CalendarMonthListResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/CalendarMonthResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/CalendarRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/CalendarService.kt
  domain/src/main/java/com/terning/domain/entity/response/CalendarScrapDetailModel.kt
  domain/src/main/java/com/terning/domain/entity/response/CalendarScrapModel.kt
  domain/src/main/java/com/terning/domain/repository/CalendarRepository.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarMonths.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarSideEffect.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarUiState.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarWeekWithScrap.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/ScreenTransition.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/WeekDaysHeader.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarDefault.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarState.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/navigation/CalendarNavigation.kt
  feature/src/main/java/com/terning/feature/calendar/models/SelectedDateState.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonth.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthScreen.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthState.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/CalendarDay.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/DayClass.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/MonthData.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/MonthModel.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarListState.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarMonthScrap.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrapListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/component/CalendarScrap.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/component/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/model/Scrap.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekState.kt
  feature/src/main/java/com/terning/feature/calendar/week/HorizontalCalendarWeek.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/main/MainTab.kt
Labels: FEAT ✨, 석준💜

#108 [FEAT/#105] 로그인 뷰 / 서버통신 구현
  app/src/main/java/com/terning/point/MyApp.kt
  app/src/main/java/com/terning/point/di/AuthInterceptor.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
Labels: FEAT ✨, FIX 🔨, 유빈💙

#104 [MOD/#84] 필터링 재설정 뷰 / 필터링 재설정 버튼 로직 수정
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/changefilter/component/ChangeFilteringRadioGroup.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
Labels: MOD ✅, UI 💐, 효빈💚

#111 [FIX/#109] 온보딩 / 서버통신 수정
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/navigation/SignUpNavigation.kt
Labels: FIX 🔨, 유빈💙

#107 [FEAT/#103] 홈 뷰 / 오늘 마감 공고 서버 통신 구현
  app/src/main/java/com/terning/point/di/DataSourceModule.kt
  app/src/main/java/com/terning/point/di/RepositoryModule.kt
  app/src/main/java/com/terning/point/di/ServiceModule.kt
  data/src/main/java/com/terning/data/datasource/HomeDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/HomeDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/HomeTodayInternResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/HomeRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/HomeService.kt
  domain/src/main/java/com/terning/domain/entity/response/HomeTodayInternModel.kt
  domain/src/main/java/com/terning/domain/repository/HomeRepository.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeSideEffect.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
Labels: FEAT ✨, 효빈💚

#112 [UI/#97] 마이페이지 뷰 / UI 구현
  app/src/main/java/com/terning/point/di/AuthInterceptor.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/button/DeleteRoundButton.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/MyPageTopAppBar.kt
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpState.kt
Labels: UI 💐, 유빈💙

#86 [FEAT/#77] 홈 뷰 / 맞춤 공고 서버 통신 구현
  data/src/main/java/com/terning/data/datasource/HomeDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/HomeDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/HomeRecommendInternResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/HomeRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/HomeService.kt
  domain/src/main/java/com/terning/domain/entity/response/HomeRecommendInternModel.kt
  domain/src/main/java/com/terning/domain/repository/HomeRepository.kt
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/model/SortBy.kt
Labels: FEAT ✨, 효빈💚

#114 [FEAT/#106] 로그아웃 / 서버통신 구현
  app/src/main/java/com/terning/point/di/DataSourceModule.kt
  app/src/main/java/com/terning/point/di/RepositoryModule.kt
  app/src/main/java/com/terning/point/di/ServiceModule.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  data/src/main/java/com/terning/data/datasource/MyPageDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/MyPageDataSourceImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/MyPageRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/MyPageService.kt
  domain/src/main/java/com/terning/domain/repository/MyPageRepository.kt
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageState.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
Labels: FEAT ✨, 유빈💙

#118 [FEAT/#116] 계정탈퇴 / 서버통신 구현
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  data/src/main/java/com/terning/data/datasource/MyPageDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/MyPageDataSourceImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/MyPageRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/MyPageService.kt
  domain/src/main/java/com/terning/domain/repository/MyPageRepository.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
Labels: FEAT ✨, 유빈💙

#120 [FEAT/#119] 마이페이지 정보 서버통신 구현
  data/src/main/java/com/terning/data/datasource/MyPageDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/MyPageDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/MyPageResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/MyPageRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/MyPageService.kt
  domain/src/main/java/com/terning/domain/entity/response/MyPageProfileModel.kt
  domain/src/main/java/com/terning/domain/repository/MyPageRepository.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageState.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
Labels: FEAT ✨, 유빈💙

#123 [HOTFIX/#117] 공고 뷰 / 공고 상세 페이지 API 수정
  data/src/main/java/com/terning/data/dto/response/InternResponseDto.kt
  domain/src/main/java/com/terning/domain/entity/response/InternInfoModel.kt
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/intern/InternViewState.kt
  feature/src/main/java/com/terning/feature/intern/component/InternBottomBar.kt
  feature/src/main/java/com/terning/feature/intern/component/ScrapCancelDialog.kt
Labels: FEAT ✨, HOTFIX 🚑️, 아린💛

#125 [FEAT/#110] 탐색 뷰 / 검색 결과 화면 API 연동
  core/src/main/java/com/terning/core/designsystem/component/item/InternItemWithShadow.kt
  data/src/main/java/com/terning/data/datasource/SearchDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/SearchDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/request/SearchRequestDto.kt
  data/src/main/java/com/terning/data/dto/response/SearchResultResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/SearchScrapsResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/SearchViewsResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/SearchRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/SearchService.kt
  domain/src/main/java/com/terning/domain/entity/response/InternshipAnnouncementModel.kt
  domain/src/main/java/com/terning/domain/entity/response/SearchResultModel.kt
  domain/src/main/java/com/terning/domain/repository/SearchRepository.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/search/SearchViewsState.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchInternList.kt
  feature/src/main/java/com/terning/feature/search/search/model/SearchScrapsListState.kt
  feature/src/main/java/com/terning/feature/search/search/model/SearchViewsListState.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessSideEffect.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchResultState.kt
Labels: FEAT ✨, 아린💛

#126 [FEAT/#121] 자동 로그인 구현
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashState.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/navigation/SplashNavigation.kt
  feature/src/main/res/drawable/ic_splash.xml
  gradle/libs.versions.toml
Labels: FEAT ✨, 유빈💙

#128 [UI/#55] 캘린더뷰 / 다이얼로그 구현
  core/src/main/java/com/terning/core/designsystem/component/dialog/TerningBasicDialog.kt
  core/src/main/java/com/terning/core/designsystem/component/item/InternItem.kt
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarUiState.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarCancelDialog.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDetailDialog.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/component/CalendarScrap.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/component/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekState.kt
Labels: UI 💐, 석준💜

#132 [FEAT/#113] 필터링 재설정 서버통신 구현
  core/src/main/java/com/terning/core/designsystem/component/button/ChangeFilterButton.kt
  data/src/main/java/com/terning/data/datasource/HomeDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/HomeDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/request/ChangeFilterRequestDto.kt
  data/src/main/java/com/terning/data/dto/response/HomeFilteringInfoResponseDto.kt
  data/src/main/java/com/terning/data/repositoryimpl/HomeRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/HomeService.kt
  domain/src/main/java/com/terning/domain/entity/request/ChangeFilteringRequestModel.kt
  domain/src/main/java/com/terning/domain/entity/response/HomeFilteringInfoModel.kt
  domain/src/main/java/com/terning/domain/repository/HomeRepository.kt
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/changefilter/component/ChangeFilteringRadioGroup.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeSideEffect.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/TerningPostItem.kt
  feature/src/main/java/com/terning/feature/home/home/model/InternData.kt
  feature/src/main/java/com/terning/feature/home/home/model/InternFilterData.kt
  feature/src/main/java/com/terning/feature/home/home/model/ScrapData.kt
  feature/src/main/java/com/terning/feature/home/home/model/UserNameState.kt
  feature/src/main/java/com/terning/feature/home/home/model/UserScrapState.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
Labels: FEAT ✨, 효빈💚

#134 [FEAT/#122] 홈 뷰 / 공고 정렬 기준 변경 구현
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
Labels: FEAT ✨, 효빈💚

#136 [FEAT/#129] 캘린더뷰 / 스크랩 서버 통신 구현
  core/src/main/java/com/terning/core/designsystem/component/topappbar/CalendarTopAppBar.kt
  data/src/main/java/com/terning/data/repositoryimpl/ScrapRepositoryImpl.kt
  domain/src/main/java/com/terning/domain/repository/ScrapRepository.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDetailDialog.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDialog.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/component/CalendarScrap.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/HorizontalCalendarWeek.kt
Labels: FEAT ✨, 석준💜

#130 [FEAT/#127] 마이페이지 뷰 / UI 및 링크 연결
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageState.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/component/MyPageItem.kt
  feature/src/main/java/com/terning/feature/mypage/navigation/MyPageNavigation.kt
  feature/src/main/res/drawable/ic_my_page_notice.xml
  feature/src/main/res/drawable/ic_my_page_opinion.xml
  feature/src/main/res/drawable/ic_my_page_version.xml
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: FEAT ✨, 유빈💙

#142 [HOTFIX/#139] 초기 필터링 오류 해결
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
Labels: HOTFIX 🚑️, 효빈💚

#145 [MOD/#143] empty 뷰 이미지 추가 및 수정
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeFilteringEmptyIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayEmptyWithImg.kt
  feature/src/main/res/drawable/ic_home_empty_filtering.xml
  feature/src/main/res/drawable/ic_home_scrap_empty.xml
  feature/src/main/res/values/strings.xml
Labels: MOD ✅, UI 💐, 효빈💚

#147 [UI/#124] 전체 그래픽 추가 작업
  app/src/main/java/com/terning/point/di/AuthInterceptor.kt
  core/build.gradle.kts
  core/src/main/assets/terning_scrap_cancel.json
  core/src/main/assets/terning_start_home.json
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SignUpBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/dialog/ScrapCancelDialogContent.kt
  core/src/main/java/com/terning/core/designsystem/component/item/TerningLottieAnimation.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/LogoTopAppBar.kt
  core/src/main/java/com/terning/core/designsystem/theme/Color.kt
  core/src/main/res/drawable/ic_character1.xml
  core/src/main/res/drawable/ic_character2.xml
  core/src/main/res/drawable/ic_character3.xml
  core/src/main/res/drawable/ic_character4.xml
  core/src/main/res/drawable/ic_character5.xml
  core/src/main/res/drawable/ic_character6.xml
  core/src/main/res/drawable/ic_sign_in_selected.xml
  core/src/main/res/drawable/ic_terning_logo_typo.xml
  core/src/main/res/drawable/ic_terning_profile_00.xml
  core/src/main/res/drawable/ic_terning_profile_01.xml
  core/src/main/res/drawable/ic_terning_profile_01_selected.png
  core/src/main/res/drawable/ic_terning_profile_02.xml
  core/src/main/res/drawable/ic_terning_profile_03.xml
  core/src/main/res/drawable/ic_terning_profile_04.xml
  core/src/main/res/drawable/ic_terning_profile_05.xml
  feature/src/main/assets/terning_start_home.json
  feature/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringScreen.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/StartHomeScreen.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/component/KakaoButton.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpProfile.kt
  feature/src/main/res/drawable/ic_terning_login.xml
  feature/src/main/res/drawable/ic_terning_mypage.xml
  feature/src/main/res/drawable/ic_terning_no_filter.xml
  feature/src/main/res/drawable/ic_terning_onboarding.xml
  feature/src/main/res/drawable/ic_terning_profile_00.xml
  feature/src/main/res/drawable/ic_terning_profile_01.xml
  feature/src/main/res/drawable/ic_terning_profile_02.xml
  feature/src/main/res/drawable/ic_terning_profile_03.xml
  feature/src/main/res/drawable/ic_terning_profile_04.xml
  feature/src/main/res/drawable/ic_terning_profile_05.xml
  feature/src/main/res/drawable/ic_terning_scrap_empty.xml
Labels: UI 💐, 유빈💙, 석준💜

#149 [HOTFIX/#148] 스플래시 배경 추가
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
Labels: HOTFIX 🚑️, UI 💐, 석준💜

#153 [UI#146] 홈 뷰 / 다이얼로그 구현
  core/src/main/java/com/terning/core/designsystem/component/item/InternItemWithShadow.kt
  core/src/main/res/values/strings.xml
  data/src/main/java/com/terning/data/dto/response/HomeRecommendInternResponseDto.kt
  domain/src/main/java/com/terning/domain/entity/response/HomeRecommendInternModel.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternDialog.kt
  feature/src/main/java/com/terning/feature/home/home/model/HomeDialogState.kt
Labels: FEAT ✨, UI 💐, 효빈💚

#155 [DOCS/#144] 리드미 작성
  README.md
Labels: DOCS 📝, 유빈💙

#156 [FIX/#150] 스크랩 1차 QA 해결
  core/src/main/java/com/terning/core/designsystem/theme/Color.kt
  data/src/main/java/com/terning/data/dto/response/SearchResultResponseDto.kt
  domain/src/main/java/com/terning/domain/entity/response/SearchResultModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDetailDialog.kt
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/src/main/java/com/terning/feature/intern/InternViewSideEffect.kt
  feature/src/main/java/com/terning/feature/intern/component/ScrapDialogContent.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchIntern.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchInternList.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessSideEffect.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchDialogState.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
  feature/src/main/res/drawable/img_ad_2.png
  feature/src/main/res/values/strings.xml
Labels: FIX 🔨, 아린💛

#157 [FIX/#154] 홈 뷰 1차 QA
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternDialog.kt
Labels: FIX 🔨, 효빈💚

#158 [FIX/#151] 캘린더 1차 QA 해결
  core/src/main/java/com/terning/core/designsystem/component/dialog/ScrapCancelDialogContent.kt
  core/src/main/java/com/terning/core/designsystem/component/dialog/TerningBasicDialog.kt
  core/src/main/java/com/terning/core/extension/LocalDateExt.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDetailDialog.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDialog.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonth.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/CalendarDay.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/CalendarMonthScrap.kt
  feature/src/main/java/com/terning/feature/calendar/scrap/component/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternDialog.kt
  feature/src/main/java/com/terning/feature/intern/component/ScrapDialogContent.kt
Labels: FIX 🔨, 석준💜

#159 [FIX/#154] 홈 뷰 1차 QA 반영
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
Labels: FIX 🔨, UI 💐, 효빈💚

#162 [FIX/#152] 온보딩, 마이페이지 1차 QA
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SignUpBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/datepicker/DatePicker.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringOneScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringThreeScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringTwoScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpProfile.kt
  feature/src/main/res/values/strings.xml
Labels: FIX 🔨, 유빈💙

#163 [FIX/#161] Home 화면에서 종료 구현
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashScreen.kt
Labels: FIX 🔨, 석준💜

#165 [UI/#164] 스플래시 변경
  feature/src/main/res/drawable/ic_splash.xml
Labels: HOTFIX 🚑️, UI 💐

#168 [HOTFIX/#166] 홈 뷰 2차 QA 반영
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternDialog.kt
Labels: HOTFIX 🚑️, 효빈💚

#169 [FIX/#167] 키보드 및 스택 관리
  core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/SearchTextField.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/StartHomeScreen.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashScreen.kt
  feature/src/main/res/values/strings.xml
Labels: HOTFIX 🚑️, 유빈💙

#170 [FIX] 색상 변경
  feature/src/main/java/com/terning/feature/intern/component/ScrapDialogContent.kt
Labels: FIX 🔨, 아린💛

#172 [FIX/#171] 스크랩 오류 수정
  feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
Labels: FIX 🔨, 석준💜

#174 [FIX/#173] 홈 뷰 / 텍스트 스타일 지정
  feature/src/main/java/com/terning/feature/home/home/component/HomeFilteringEmptyIntern.kt
Labels: FIX 🔨, 효빈💚
