Repository teamterning/Terning-Android, pull requests merged in 2024-08, with the labels that each got.

#179 [FEAT/#175] 컴포넌트 문서화
  .github/workflows/dokka.yml
  app/build.gradle.kts
  build.gradle.kts
  core/build.gradle.kts
  core/docs.md
  core/src/main/java/com/terning/core/designsystem/component/button/TerningBasicButton.kt
  gradle/libs.versions.toml
Labels: DOCS 📝, FEAT ✨, 유빈💙

#182 [REFACTOR/#181] 월간 캘린더 리팩토링
  data/src/main/java/com/terning/data/datasource/ScrapDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/ScrapDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/CalendarDayListResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/CalendarMonthListResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/CalendarMonthResponseDto.kt
  data/src/main/java/com/terning/data/mapper/CalendarScrapDetailListMapper.kt
  data/src/main/java/com/terning/data/mapper/CalendarScrapDetailMapper.kt
  data/src/main/java/com/terning/data/mapper/CalendarScrapMapper.kt
  data/src/main/java/com/terning/data/repositoryimpl/CalendarRepositoryImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/ScrapRepositoryImpl.kt
  domain/src/main/java/com/terning/domain/entity/CalendarScrap.kt
  domain/src/main/java/com/terning/domain/entity/CalendarScrapDetail.kt
  domain/src/main/java/com/terning/domain/entity/CalendarScrapRequest.kt
  domain/src/main/java/com/terning/domain/entity/request/ScrapRequestModel.kt
  domain/src/main/java/com/terning/domain/repository/CalendarRepository.kt
  domain/src/main/java/com/terning/domain/repository/ScrapRepository.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDay.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDetailDialog.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarState.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarUiState.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/list/component/CalendarScrap.kt
  feature/src/main/java/com/terning/feature/calendar/list/component/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/calendar/list/model/CalendarListState.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthScreen.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/CalendarMonth.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/CalendarMonthScrap.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/HorizontalCalendar.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/CalendarMonthState.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/DayModel.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/MonthData.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/MonthModel.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/MonthUiState.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/component/HorizontalCalendarWeek.kt
  feature/src/main/java/com/terning/feature/calendar/week/model/CalendarWeekState.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/res/values/strings.xml
Labels: REFACTOR ♻️, 석준💜

#187 [REFACTOR/#180] 온보딩, 필터링, 마이페이지 / 리팩토링
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SignUpBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/TerningBasicBottomSheet.kt
  data/src/main/java/com/terning/data/datasource/TokenReissueDataSource.kt
  data/src/main/java/com/terning/data/dto/request/FilteringRequestDto.kt
  data/src/main/java/com/terning/data/dto/request/SignInRequestDto.kt
  data/src/main/java/com/terning/data/dto/request/SignUpRequestDto.kt
  data/src/main/java/com/terning/data/dto/response/MyPageResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/SignInResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/SignUpResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/TokenReissueResponseDto.kt
  data/src/main/java/com/terning/data/mapper/auth/TokenReissueMapper.kt
  data/src/main/java/com/terning/data/mapper/filtering/FilteringMapper.kt
  data/src/main/java/com/terning/data/mapper/mypage/MyPageMapper.kt
  data/src/main/java/com/terning/data/mapper/onboarding/SignInRequestMapper.kt
  data/src/main/java/com/terning/data/mapper/onboarding/SignInResponseMapper.kt
  data/src/main/java/com/terning/data/mapper/onboarding/SignUpRequestMapper.kt
  data/src/main/java/com/terning/data/mapper/onboarding/SignUpResponseMapper.kt
  data/src/main/java/com/terning/data/repositoryimpl/AuthRepositoryImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/FilteringRepositoryImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/MyPageRepositoryImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/TokenReissueRepositoryImpl.kt
  domain/src/main/java/com/terning/domain/entity/auth/TokenReissue.kt
  domain/src/main/java/com/terning/domain/entity/filtering/Filtering.kt
  domain/src/main/java/com/terning/domain/entity/mypage/MyPageProfileModel.kt
  domain/src/main/java/com/terning/domain/entity/onboarding/SignInRequest.kt
  domain/src/main/java/com/terning/domain/entity/onboarding/SignInResponse.kt
  domain/src/main/java/com/terning/domain/entity/onboarding/SignUpRequest.kt
  domain/src/main/java/com/terning/domain/entity/onboarding/SignUpResponse.kt
  domain/src/main/java/com/terning/domain/entity/request/SignInRequestModel.kt
  domain/src/main/java/com/terning/domain/entity/response/TokenReissueResponseModel.kt
  domain/src/main/java/com/terning/domain/repository/AuthRepository.kt
  domain/src/main/java/com/terning/domain/repository/FilteringRepository.kt
  domain/src/main/java/com/terning/domain/repository/MyPageRepository.kt
  domain/src/main/java/com/terning/domain/repository/TokenReissueRepository.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringOneScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringThreeScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringTwoScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringViewModel.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/navigation/FilteringThreeNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringScreen.kt
  feature/src/main/java/com/terning/feature/filtering/startfiltering/navigation/StartFilteringNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/StartHomeScreen.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashState.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/navigation/SplashNavigation.kt
Labels: REFACTOR ♻️, 유빈💙

#189 [REFACTOR/#188] 컴포넌트 문서화 및 추가 리팩토링
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SignUpBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/TerningBasicBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/button/DeleteRoundButton.kt
  core/src/main/java/com/terning/core/designsystem/component/button/FilteringButton.kt
  core/src/main/java/com/terning/core/designsystem/component/button/RectangleButton.kt
  core/src/main/java/com/terning/core/designsystem/component/button/RoundButton.kt
  core/src/main/java/com/terning/core/designsystem/component/datepicker/DatePicker.kt
  core/src/main/java/com/terning/core/designsystem/component/image/TerningImage.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringOneScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringThreeRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringTwoScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/component/StatusOneRadioGroup.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/component/StatusTwoRadioGroup.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/navigation/FilteringOneNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/navigation/FilteringThreeNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/navigation/FilteringTwoNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringScreen.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/StartHomeScreen.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/navigation/StartHomeNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/component/MyPageItem.kt
  feature/src/main/java/com/terning/feature/mypage/navigation/MyPageNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInSideEffect.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/component/KakaoButton.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/navigation/SignInNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpProfile.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/navigation/SignUpNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/navigation/SplashNavigation.kt
Labels: DOCS 📝, REFACTOR ♻️, 유빈💙

#195 [Refactor/#186] 탐색 기본 뷰 / 리팩토링
  core/src/main/java/com/terning/core/designsystem/component/textfield/SearchTextField.kt
  data/src/main/java/com/terning/data/datasource/SearchDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/SearchDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/SearchAnnouncementResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/SearchResultResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/SearchViewsResponseDto.kt
  data/src/main/java/com/terning/data/mapper/search/SearchAnnouncementListMapper.kt
  data/src/main/java/com/terning/data/mapper/search/SearchResultMapper.kt
  data/src/main/java/com/terning/data/repositoryimpl/SearchRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/SearchService.kt
  domain/src/main/java/com/terning/domain/entity/search/SearchPopularAnnouncement.kt
  domain/src/main/java/com/terning/domain/entity/search/SearchResult.kt
  domain/src/main/java/com/terning/domain/repository/SearchRepository.kt
  feature/src/main/java/com/terning/feature/intern/navigation/InternNavigation.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchIntern.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchInternList.kt
  feature/src/main/java/com/terning/feature/search/search/model/SearchScrapsListState.kt
  feature/src/main/java/com/terning/feature/search/search/model/SearchViewsListState.kt
  feature/src/main/java/com/terning/feature/search/search/navigation/SearchNavigation.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchResultState.kt
Labels: REFACTOR ♻️, 아린💛

#197 [ADD/#196] 릴리즈 서버 추가
  app/build.gradle.kts
Labels: ADD ➕, 유빈💙

#192 [CHORE/#177] 홈 뷰 패키지 구조 수정
  data/src/main/java/com/terning/data/dto/response/HomeFilteringInfoResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/HomeRecommendInternResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/HomeTodayInternResponseDto.kt
  data/src/main/java/com/terning/data/mapper/home/HomeFilteringInfoMapper.kt
  data/src/main/java/com/terning/data/mapper/home/HomeRecommendInternMapper.kt
  data/src/main/java/com/terning/data/mapper/home/HomeTodayInternMapper.kt
  data/src/main/java/com/terning/data/repositoryimpl/HomeRepositoryImpl.kt
  domain/src/main/java/com/terning/domain/entity/home/HomeFilteringInfo.kt
  domain/src/main/java/com/terning/domain/entity/home/HomeRecommendIntern.kt
  domain/src/main/java/com/terning/domain/entity/home/HomeTodayIntern.kt
  domain/src/main/java/com/terning/domain/repository/HomeRepository.kt
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternDialog.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
Labels: CHORE 🎀, 효빈💚

#199 [FIX/#198] 릴리즈 모드 수정
  app/build.gradle.kts
  core/build.gradle.kts
  feature/build.gradle.kts
  gradle/libs.versions.toml
Labels: FIX 🔨, 유빈💙

#200 [REFACTOR/#183] 캘린더 리팩토링
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarSideEffect.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDialog.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarUiState.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/navigation/CalendarNavigation.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListSideEffect.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/list/component/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/calendar/list/model/CalendarListState.kt
  feature/src/main/java/com/terning/feature/calendar/list/model/CalendarListUiState.kt
  feature/src/main/java/com/terning/feature/calendar/list/model/Scrap.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthScreen.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthSideEffect.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/HorizontalCalendar.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/CalendarMonthUiState.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/MonthModel.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekSideEffect.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/week/component/HorizontalCalendarWeek.kt
  feature/src/main/java/com/terning/feature/calendar/week/model/CalendarWeekState.kt
  feature/src/main/java/com/terning/feature/calendar/week/model/CalendarWeekUiState.kt
Labels: REFACTOR ♻️, 석준💜

#203 [REFACTOR/#193] 홈 뷰 리팩토링
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeState.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
  feature/src/main/res/drawable/ic_terning_logo_typo.xml
Labels: REFACTOR ♻️, 효빈💚

#211 [FIX/#210] 버전 코드 업데이트
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: FIX 🔨, 유빈💙

#205 [UI/#202] 마이페이지 뷰 / UI 수정
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/button/DeleteRoundButton.kt
  feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/component/MyPageItem.kt
  feature/src/main/java/com/terning/feature/mypage/component/MyPageProfile.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpProfile.kt
  feature/src/main/res/drawable/ic_my_page.xml
  feature/src/main/res/drawable/ic_my_page_go_detail.xml
  feature/src/main/res/drawable/ic_my_page_go_edit.xml
  feature/src/main/res/drawable/ic_my_page_line.xml
  feature/src/main/res/drawable/ic_terning_mypage.xml
  feature/src/main/res/drawable/img_terning_point.png
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 유빈💙
