Repository teamterning/Terning-Android, pull requests merged in 2024-09, with the labels that each got.

#209 [FEAT/#208] 테스트 서버 주소 추가 / 온보딩 서버통신 수정
  app/build.gradle.kts
  app/src/main/java/com/terning/point/di/AuthInterceptor.kt
  data/src/main/java/com/terning/data/dto/response/TokenReissueResponseDto.kt
  data/src/main/java/com/terning/data/mapper/auth/TokenReissueMapper.kt
  domain/src/main/java/com/terning/domain/entity/auth/TokenReissue.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpState.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
Labels: FEAT ✨, 유빈💙

#217 [FIX/#216] 테스트 서버 / 접근 권한 추가
  .github/workflows/dokka.yml
  .github/workflows/pr_checker.yml
Labels: FIX 🔨, 유빈💙

#207 [UI/#206] 프로필 수정 뷰 / UI 구현
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/ProfileBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/item/ProfileWithPlusButton.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  core/src/main/java/com/terning/core/util/Regex.kt
  core/src/main/res/drawable/ic_name_text_field_check.xml
  core/src/main/res/drawable/ic_name_text_field_error.xml
  core/src/main/res/drawable/ic_sign_up_button.xml
  core/src/main/res/values/strings.xml
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringOneScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringThreeRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/FilteringTwoScreen.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/navigation/FilteringOneNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/navigation/FilteringThreeNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/filtering/navigation/FilteringTwoNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringScreen.kt
  feature/src/main/java/com/terning/feature/filtering/startfiltering/navigation/StartFilteringNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/StartHomeScreen.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/navigation/StartHomeNavigation.kt
  feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
  feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/home/navigation/HometNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/main/MainTab.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageSideEffect.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageState.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/component/MyPageItem.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/component/MyPageProfile.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/navigation/MyPageNavigation.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditRoute.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditSideEffect.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditState.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/navigation/ProfileEditNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/navigation/SignInNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpState.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/navigation/SignUpNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/navigation/SplashNavigation.kt
  feature/src/main/res/drawable/ic_my_page_notice.xml
  feature/src/main/res/drawable/ic_my_page_opinion.xml
  feature/src/main/res/drawable/ic_my_page_personal.xml
  feature/src/main/res/drawable/ic_my_page_service.xml
  feature/src/main/res/drawable/ic_my_page_version.xml
  feature/src/main/res/drawable/ic_terning_profile_00.xml
  feature/src/main/res/drawable/ic_terning_profile_01.xml
  feature/src/main/res/drawable/ic_terning_profile_02.xml
  feature/src/main/res/drawable/ic_terning_profile_03.xml
  feature/src/main/res/drawable/ic_terning_profile_04.xml
  feature/src/main/res/drawable/ic_terning_profile_05.xml
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 유빈💙

#213 [REFACTOR/#212] 다이얼로그 / 리팩토링
  core/src/main/java/com/terning/core/designsystem/component/dialog/TerningBasicDialog.kt
  core/src/main/java/com/terning/core/designsystem/component/item/RadioButtonGroups.kt
  core/src/main/java/com/terning/core/designsystem/theme/Color.kt
  core/src/main/java/com/terning/core/extension/TextStyle.kt
  core/src/main/java/com/terning/core/type/ColorType.kt
  core/src/main/res/values/strings.xml
  feature/src/main/assets/terning_scrap_cancel.json
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarCancelDialog.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/component/CalendarDetailDialog.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekViewModel.kt
  feature/src/main/java/com/terning/feature/dialog/cancel/ScrapCancelDialog.kt
  feature/src/main/java/com/terning/feature/dialog/cancel/ScrapCancelSideEffect.kt
  feature/src/main/java/com/terning/feature/dialog/cancel/ScrapCancelViewModel.kt
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialogSideEffect.kt
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialogViewModel.kt
  feature/src/main/java/com/terning/feature/dialog/detail/component/ColorPalette.kt
  feature/src/main/java/com/terning/feature/dialog/detail/component/ScrapColorChangeButton.kt
  feature/src/main/java/com/terning/feature/dialog/detail/state/ScrapDialogUiState.kt
  feature/src/main/res/values/strings.xml
Labels: REFACTOR ♻️, 석준💜

#224 [UI/#223] 온보딩 그래픽 추가
  core/src/main/java/com/terning/core/designsystem/component/item/TerningLottieAnimation.kt
  feature/src/main/assets/terning_onboarding_start.json
  feature/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringRoute.kt
Labels: ADD ➕, UI 💐, 석준💜

#222 [UI/#214] 달력 / 2차 스프린트
  core/src/main/java/com/terning/core/designsystem/component/topappbar/CalendarTopAppBar.kt
  core/src/main/java/com/terning/core/extension/Modifier.kt
  data/src/main/java/com/terning/data/datasource/ScrapDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/ScrapDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/CalendarDayListResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/CalendarMonthListResponseDto.kt
  data/src/main/java/com/terning/data/dto/response/CalendarMonthResponseDto.kt
  data/src/main/java/com/terning/data/mapper/CalendarScrapDetailListMapper.kt
  data/src/main/java/com/terning/data/mapper/CalendarScrapDetailMapper.kt
  data/src/main/java/com/terning/data/mapper/CalendarScrapMapper.kt
  data/src/main/java/com/terning/data/repositoryimpl/CalendarRepositoryImpl.kt
  data/src/main/java/com/terning/data/repositoryimpl/ScrapRepositoryImpl.kt
  domain/src/main/java/com/terning/domain/entity/calendar/CalendarScrap.kt
  domain/src/main/java/com/terning/domain/entity/calendar/CalendarScrapDetail.kt
  domain/src/main/java/com/terning/domain/entity/calendar/CalendarScrapRequest.kt
  domain/src/main/java/com/terning/domain/repository/CalendarRepository.kt
  domain/src/main/java/com/terning/domain/repository/ScrapRepository.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/navigation/CalendarNavigation.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/list/component/CalendarScrap.kt
  feature/src/main/java/com/terning/feature/calendar/list/component/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/calendar/list/model/CalendarListUiState.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthScreen.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/CalendarMonth.kt
  feature/src/main/java/com/terning/feature/calendar/month/component/CalendarMonthScrap.kt
  feature/src/main/java/com/terning/feature/calendar/month/model/CalendarMonthUiState.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/week/model/CalendarWeekUiState.kt
  feature/src/main/java/com/terning/feature/dialog/cancel/ScrapCancelDialog.kt
  feature/src/main/java/com/terning/feature/dialog/cancel/ScrapCancelViewModel.kt
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialogViewModel.kt
  feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/res/drawable/ic_terning_calendar_empty.xml
Labels: MOD ✅, UI 💐, 석준💜

#228 [Fix/#226] 프로필 수정 뷰 / 서버통신 수정
  core/src/main/java/com/terning/core/type/ProfileImage.kt
  data/src/main/java/com/terning/data/datasourceimpl/MyPageDataSourceImpl.kt
  data/src/main/java/com/terning/data/datasourceimpl/TokenReissueDataSourceImpl.kt
  data/src/main/java/com/terning/data/service/MyPageService.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditState.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditViewModel.kt
Labels: FIX 🔨, 유빈💙

#234 [UI/#229] 검색 뷰 / UI 수정
  core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/LogoTopAppBar.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchInternList.kt
  feature/src/main/java/com/terning/feature/search/search/navigation/SearchNavigation.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchDialogState.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/navigation/SearchProcessNavigation.kt
  feature/src/main/res/drawable/ic_search_18.xml
  feature/src/main/res/drawable/ic_search_backgroud.xml
  feature/src/main/res/drawable/ic_search_bg.xml
  feature/src/main/res/drawable/ic_search_empty.xml
  feature/src/main/res/values/strings.xml
Labels: UI 💐, 아린💛

#230 [REFACTOR/#220] 공고 상세 뷰 / 리팩토링
  data/src/main/java/com/terning/data/dto/response/InternResponseDto.kt
  data/src/main/java/com/terning/data/mapper/intern/InternInfoMapper.kt
  data/src/main/java/com/terning/data/repositoryimpl/InternRepositoryImpl.kt
  domain/src/main/java/com/terning/domain/entity/intern/InternInfo.kt
  domain/src/main/java/com/terning/domain/repository/InternRepository.kt
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/src/main/java/com/terning/feature/intern/component/InternBottomBar.kt
  feature/src/main/java/com/terning/feature/intern/component/ScrapDialogContent.kt
  feature/src/main/java/com/terning/feature/intern/model/InternUiState.kt
  feature/src/main/java/com/terning/feature/intern/navigation/InternNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
Labels: UI 💐, 아린💛

#237 [ADD/#201] 공통 컴포넌트 문서화
  core/src/main/java/com/terning/core/designsystem/component/dialog/ScrapCancelDialogContent.kt
  core/src/main/java/com/terning/core/designsystem/component/dialog/TerningBasicDialog.kt
  core/src/main/java/com/terning/core/designsystem/component/item/ColorPalette.kt
  core/src/main/java/com/terning/core/designsystem/component/item/InternItem.kt
  core/src/main/java/com/terning/core/designsystem/component/item/ScrapBox.kt
  core/src/main/java/com/terning/core/designsystem/component/item/TerningLottieAnimation.kt
  core/src/main/java/com/terning/core/designsystem/component/topappbar/CalendarTopAppBar.kt
  feature/src/main/java/com/terning/feature/intern/component/InternCancelDialog.kt
Labels: ADD ➕, 석준💜

#242 [FIX/#233] 온보딩 필터링 설정 / 서버통신 수정
  data/src/main/java/com/terning/data/dto/request/FilteringRequestDto.kt
  domain/src/main/java/com/terning/domain/entity/filtering/Filtering.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/FilteringOneRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/FilteringOneSideEffect.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/FilteringOneState.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/FilteringOneViewModel.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/component/StatusOneRadioGroup.kt
  feature/src/main/java/com/terning/feature/filtering/filteringthree/FilteringThreeRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filteringthree/FilteringThreeState.kt
  feature/src/main/java/com/terning/feature/filtering/filteringthree/FilteringThreeViewModel.kt
  feature/src/main/java/com/terning/feature/filtering/filteringthree/navigation/FilteringThreeNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/FilteringTwoRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/FilteringTwoSideEffect.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/FilteringTwoState.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/FilteringTwoViewModel.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/component/StatusTwoRadioGroup.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/navigation/FilteringTwoNavigation.kt
Labels: FIX 🔨, 유빈💙

#245 [MOD/#244] 다이얼로그 버튼 수정
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialogViewModel.kt
  feature/src/main/java/com/terning/feature/dialog/detail/component/ColorPalette.kt
  feature/src/main/java/com/terning/feature/dialog/detail/component/ScrapColorChangeButton.kt
  feature/src/main/java/com/terning/feature/dialog/detail/component/ScrapInfoRow.kt
  feature/src/main/java/com/terning/feature/dialog/detail/state/ScrapDialogUiState.kt
Labels: MOD ✅, 석준💜

#251 [FIX/#241] 유빈 담당 뷰 / 1차 QA 반영
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/ProfileBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/button/FilteringButton.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
  core/src/main/java/com/terning/core/type/ProfileImage.kt
  core/src/main/res/drawable/ic_terning_selected_profile_00.xml
  core/src/main/res/drawable/ic_terning_selected_profile_01.xml
  core/src/main/res/drawable/ic_terning_selected_profile_02.xml
  core/src/main/res/drawable/ic_terning_selected_profile_03.xml
  core/src/main/res/drawable/ic_terning_selected_profile_04.xml
  core/src/main/res/drawable/ic_terning_selected_profile_05.xml
  feature/src/main/java/com/terning/feature/filtering/filteringone/FilteringOneRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/FilteringOneViewModel.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/component/StatusOneRadioGroup.kt
  feature/src/main/java/com/terning/feature/filtering/filteringone/navigation/FilteringOneNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/filteringthree/FilteringThreeRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filteringthree/navigation/FilteringThreeNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/FilteringTwoRoute.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/FilteringTwoViewModel.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/component/StatusTwoRadioGroup.kt
  feature/src/main/java/com/terning/feature/filtering/filteringtwo/navigation/FilteringTwoNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringRoute.kt
  feature/src/main/java/com/terning/feature/filtering/startfiltering/navigation/StartFilteringNavigation.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/StartHomeRoute.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/navigation/StartHomeNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageSideEffect.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageState.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/navigation/MyPageNavigation.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditRoute.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditState.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditViewModel.kt
  feature/src/main/java/com/terning/feature/mypage/profileedit/navigation/ProfileEditNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/navigation/SignInNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signup/navigation/SignUpNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/SplashRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/navigation/SplashNavigation.kt
  feature/src/main/res/values/strings.xml
Labels: FIX 🔨, 유빈💙

#249 [FIX/#239] 공고 상세 뷰 / QA 수정사항 반영
  data/src/main/java/com/terning/data/dto/response/InternResponseDto.kt
  data/src/main/java/com/terning/data/mapper/intern/InternInfoMapper.kt
  domain/src/main/java/com/terning/domain/entity/intern/InternInfo.kt
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/src/main/java/com/terning/feature/intern/component/InternBottomBar.kt
  feature/src/main/java/com/terning/feature/intern/component/InternInfoRow.kt
  feature/src/main/java/com/terning/feature/intern/model/InternUiState.kt
  feature/src/main/java/com/terning/feature/intern/navigation/InternNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
Labels: FIX 🔨, 아린💛

#248 [REFACTOR/#246] 달력 로직 대폭 수정
  core/src/main/java/com/terning/core/designsystem/component/topappbar/CalendarTopAppBar.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarDefault.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/model/CalendarUiState.kt
  feature/src/main/java/com/terning/feature/calendar/calendar/navigation/CalendarNavigation.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/list/component/CalendarScrapList.kt
  feature/src/main/java/com/terning/feature/calendar/list/model/CalendarListUiState.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthScreen.kt
  feature/src/main/java/com/terning/feature/calendar/month/CalendarMonthViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekViewModel.kt
  feature/src/main/java/com/terning/feature/calendar/week/component/HorizontalCalendarWeek.kt
  feature/src/main/java/com/terning/feature/calendar/week/model/CalendarWeekUiState.kt
Labels: REFACTOR ♻️, 석준💜

#254 [FIX/#253] 프로필 수정 뷰 / 수정 조건 수정
  feature/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditViewModel.kt
Labels: FIX 🔨, 유빈💙

#252 [FIX/#250] 탐색 뷰 / QA 수정사항 반영
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SortingBottomSheet.kt
  core/src/main/java/com/terning/core/designsystem/component/textfield/SearchTextField.kt
  data/src/main/java/com/terning/data/dto/response/SearchResultResponseDto.kt
  data/src/main/java/com/terning/data/mapper/search/SearchResultMapper.kt
  domain/src/main/java/com/terning/domain/entity/search/SearchResult.kt
  feature/src/main/java/com/terning/feature/calendar/list/CalendarListScreen.kt
  feature/src/main/java/com/terning/feature/calendar/week/CalendarWeekScreen.kt
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
  feature/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
Labels: FIX 🔨, 아린💛

#256 [FIX/#247] 홈 뷰 / 추가 수정사항 반영
  core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SortingBottomSheet.kt
  data/src/main/java/com/terning/data/datasource/HomeDataSource.kt
  data/src/main/java/com/terning/data/datasourceimpl/HomeDataSourceImpl.kt
  data/src/main/java/com/terning/data/dto/response/HomeUpcomingInternResponseDto.kt
  data/src/main/java/com/terning/data/mapper/home/HomeUpcomingInternMapper.kt
  data/src/main/java/com/terning/data/repositoryimpl/HomeRepositoryImpl.kt
  data/src/main/java/com/terning/data/service/HomeService.kt
  domain/src/main/java/com/terning/domain/entity/home/HomeUpcomingIntern.kt
  domain/src/main/java/com/terning/domain/repository/HomeRepository.kt
  feature/src/main/java/com/terning/feature/filtering/starthome/navigation/StartHomeNavigation.kt
  feature/src/main/java/com/terning/feature/home/HomeRoute.kt
  feature/src/main/java/com/terning/feature/home/HomeSideEffect.kt
  feature/src/main/java/com/terning/feature/home/HomeState.kt
  feature/src/main/java/com/terning/feature/home/HomeViewModel.kt
  feature/src/main/java/com/terning/feature/home/component/HomeFilteringBottomSheet.kt
  feature/src/main/java/com/terning/feature/home/component/HomeFilteringScreen.kt
  feature/src/main/java/com/terning/feature/home/component/HomeRecommendEmptyIntern.kt
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingEmptyFilter.kt
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingEmptyIntern.kt
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingInternScreen.kt
  feature/src/main/java/com/terning/feature/home/model/HomeDialogState.kt
  feature/src/main/java/com/terning/feature/home/navigation/HometNavigation.kt
  feature/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/src/main/java/com/terning/feature/main/MainTab.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/navigation/SignInNavigation.kt
  feature/src/main/java/com/terning/feature/onboarding/splash/navigation/SplashNavigation.kt
Labels: FIX 🔨, 효빈💚

#259 [FIX/#255] 회원가입 / 서버통신 수정
  data/src/main/java/com/terning/data/datasourceimpl/AuthDataSourceImpl.kt
  data/src/main/java/com/terning/data/service/AuthService.kt
Labels: FIX 🔨, 유빈💙

#258 [FIX/#257] 홈 뷰 / 맞춤 공고 api 수정사항 반영
  data/src/main/java/com/terning/data/dto/response/HomeRecommendInternResponseDto.kt
Labels: FIX 🔨, 효빈💚

#261 [MOD/#260] 로티, 이미지 변경 및 탐색뷰 광고 배너 링크 연결
  core/src/main/assets/terning_scrap_cancel.json
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
  feature/src/main/res/drawable/img_ad_2.png
Labels: MOD ✅, UI 💐, 효빈💚

#265 [FIX/#263] 홈 뷰 / 2차 QA 반영
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingEmptyFilter.kt
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingInternScreen.kt
  feature/src/main/res/drawable/ic_home_scrap_empty.png
  feature/src/main/res/drawable/ic_home_scrap_empty.xml
Labels: FIX 🔨, 효빈💚

#269 [FIX/#267] 탐색 뷰 / 2차 QA 반영
  feature/src/main/java/com/terning/feature/intern/component/InternTitle.kt
  feature/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchIntern.kt
  feature/src/main/res/values/strings.xml
Labels: FIX 🔨, 아린💛

#266 [FIX/#264] 온보딩 뷰 / 2차 QA 반영
  app/build.gradle.kts
  core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
  feature/build.gradle.kts
  feature/src/main/assets/terning_sign_in.json
  feature/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/util/MyPageDefaults.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
  feature/src/main/java/com/terning/feature/onboarding/signin/component/KakaoButton.kt
  feature/src/main/res/drawable/ic_terning_login.xml
  gradle/libs.versions.toml
Labels: FIX 🔨, 유빈💙

#272 [FIX/#271] CI/CD 수정
  .github/workflows/dokka.yml
  .github/workflows/pr_checker.yml
Labels: FIX 🔨, 유빈💙
