Repository teamterning/Terning-Android, pull requests merged in 2024-10, with the labels that each got.

#276 [FIX/#273] 다이얼로그 QA 반영
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
  feature/src/main/res/values/strings.xml
Labels: FIX 🔨, 석준💜

#277 [FIX/#274] 온보딩, 마이페이지 / 최종 QA
  app/src/main/AndroidManifest.xml
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
  feature/src/main/java/com/terning/feature/mypage/mypage/component/MyPageItem.kt
  feature/src/main/res/mipmap-hdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-hdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-hdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-mdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-mdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-mdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-xhdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-xhdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-xhdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-xxhdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-xxhdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-xxhdpi/ic_terning_launcher_round.webp
  feature/src/main/res/mipmap-xxxhdpi/ic_terning_launcher.webp
  feature/src/main/res/mipmap-xxxhdpi/ic_terning_launcher_foreground.webp
  feature/src/main/res/mipmap-xxxhdpi/ic_terning_launcher_round.webp
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: FIX 🔨, 유빈💙

#281 [DOCS/#262] 리드미 수정
  README.md
Labels: DOCS 📝, 유빈💙

#282 [FIX/#275] 탐색 뷰 최종 QA
  feature/src/main/java/com/terning/feature/intern/component/InternTitle.kt
  feature/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
  feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
Labels: FIX 🔨, 아린💛

#284 [FIX/#279] 홈 뷰 최종 QA 반영
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingEmptyFilter.kt
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingEmptyIntern.kt
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingInternScreen.kt
Labels: FIX 🔨, 효빈💚

#285 [FIX/#283] 릴리즈 마지막 작업
  feature/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
  gradle/libs.versions.toml
Labels: FIX 🔨, 유빈💙

#290 [FIX/#286] 공고 아이템 사진 / 오류 수정
  core/build.gradle.kts
  core/src/main/java/com/terning/core/designsystem/component/datepicker/DatePicker.kt
  core/src/main/java/com/terning/core/designsystem/component/item/InternItem.kt
  feature/build.gradle.kts
  feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
  feature/src/main/java/com/terning/feature/home/component/HomeUpcomingInternScreen.kt
  feature/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
  feature/src/main/java/com/terning/feature/search/search/component/SearchIntern.kt
  gradle/libs.versions.toml
Labels: FIX 🔨, 유빈💙

#292 [MOD/#291] 버전 업데이트 1.1.4 -> 1.1.5
  gradle/libs.versions.toml
Labels: MOD ✅, 유빈💙

#297 [FIX/#296] DateTimeException 해결
  feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
Labels: FIX 🔨, 석준💜

#299 [MOD/#298] 배너 이미지 변경
  domain/src/main/java/com/terning/domain/entity/search/SearchBanner.kt
  feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/src/main/java/com/terning/feature/search/search/SearchViewModel.kt
  feature/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
  feature/src/main/res/drawable/img_ad_1.png
  feature/src/main/res/drawable/img_ad_2.png
  feature/src/main/res/drawable/img_ad_3.png
  gradle/libs.versions.toml
Labels: MOD ✅, UI 💐, 석준💜
