Repository teamterning/Terning-Android, pull requests merged in 2025-04, with the labels that each got.

#370 [UI/#359] 탐색, 공고 뷰 / 로딩 이미지 추가
  core/designsystem/src/main/res/drawable/ic_terning_intern_item_image_loading_128.xml
  core/designsystem/src/main/res/drawable/ic_terning_intern_item_image_loading_popular.xml
  domain/intern/src/main/java/com/terning/domain/intern/entity/InternInfo.kt
  feature/intern/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/intern/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/intern/src/main/java/com/terning/feature/intern/InternViewSideEffect.kt
  feature/intern/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
  feature/search/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/search/src/main/java/com/terning/feature/search/search/component/BannerSlider.kt
  feature/search/src/main/java/com/terning/feature/search/search/component/SearchIntern.kt
  feature/search/src/main/res/raw/terning_banner_loading.json
Labels: UI 💐, 아린💛

#366 [UI/#357] 홈페이지 로딩 인디케이터
  build-logic/src/main/java/com/terning/build_logic/convention/ComposeAndroid.kt
  core/designsystem/src/main/res/raw/paging_loading_animation.json
  feature/home/src/main/java/com/terning/feature/home/HomeRoute.kt
Labels: UI 💐, 석준💜

#367 [UI/#361] 업데이트 다이얼로그 UI 구현
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/terning/feature/onboarding/splash/component/TerningUpdateDialog.kt
  feature/onboarding/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: UI 💐, 석준💜

#371 [FEAT/#368] 업데이트 팝업 로직
  app/build.gradle.kts
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/terning/core/designsystem/extension/ContextExt.kt
  core/firebase/src/main/java/com/terning/core/firebase/remoteconfig/RemoteConfigKey.kt
  core/firebase/src/main/java/com/terning/core/firebase/remoteconfig/RemoteConfigModule.kt
  core/firebase/src/main/java/com/terning/core/firebase/remoteconfig/TerningRemoteConfig.kt
  data/update/.gitignore
  data/update/build.gradle.kts
  data/update/src/main/AndroidManifest.xml
  data/update/src/main/java/com/terning/data/update/datasource/UpdateDataSource.kt
  data/update/src/main/java/com/terning/data/update/di/RepositoryModule.kt
  data/update/src/main/java/com/terning/data/update/repositoryimpl/UpdateRepositoryImpl.kt
  domain/update/.gitignore
  domain/update/build.gradle.kts
  domain/update/src/main/java/com/terning/domain/update/entity/UpdateMessage.kt
  domain/update/src/main/java/com/terning/domain/update/entity/UpdateState.kt
  domain/update/src/main/java/com/terning/domain/update/repository/UpdateRepository.kt
  domain/update/src/main/java/com/terning/domain/update/usecase/GetAppVersionUseCase.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/terning/feature/onboarding/splash/SplashRoute.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/splash/SplashViewModel.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/splash/component/TerningUpdateDialog.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEAT ✨, UI 💐, 석준💜

#374 [HOTFIX] 업데이트 로직 develop에 머지
  app/build.gradle.kts
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/terning/core/designsystem/extension/ContextExt.kt
  core/firebase/src/main/java/com/terning/core/firebase/remoteconfig/RemoteConfigKey.kt
  core/firebase/src/main/java/com/terning/core/firebase/remoteconfig/RemoteConfigModule.kt
  core/firebase/src/main/java/com/terning/core/firebase/remoteconfig/TerningRemoteConfig.kt
  data/update/.gitignore
  data/update/build.gradle.kts
  data/update/src/main/AndroidManifest.xml
  data/update/src/main/java/com/terning/data/update/datasource/UpdateDataSource.kt
  data/update/src/main/java/com/terning/data/update/di/RepositoryModule.kt
  data/update/src/main/java/com/terning/data/update/repositoryimpl/UpdateRepositoryImpl.kt
  domain/update/.gitignore
  domain/update/build.gradle.kts
  domain/update/src/main/java/com/terning/domain/update/entity/UpdateMessage.kt
  domain/update/src/main/java/com/terning/domain/update/entity/UpdateState.kt
  domain/update/src/main/java/com/terning/domain/update/repository/UpdateRepository.kt
  domain/update/src/main/java/com/terning/domain/update/usecase/GetAppVersionUseCase.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/terning/feature/onboarding/splash/SplashRoute.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/splash/SplashViewModel.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/splash/component/TerningUpdateDialog.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: HOTFIX 🚑️, 석준💜

#379 [FEAT/#378] 회원가입 / FCM 서버통신 구현
  app/build.gradle.kts
  core/firebase/build.gradle.kts
  core/firebase/src/main/java/com/terning/core/firebase/di/FcmTokenModule.kt
  core/firebase/src/main/java/com/terning/core/firebase/di/RemoteConfigModule.kt
  core/firebase/src/main/java/com/terning/core/firebase/fcmtoken/FcmTokenProvider.kt
  core/firebase/src/main/java/com/terning/core/firebase/fcmtoken/FcmTokenProviderImpl.kt
  core/firebase/src/main/java/com/terning/core/firebase/messageservice/TerningMessagingService.kt
  core/firebase/src/main/java/com/terning/core/firebase/remoteconfig/RemoteConfigModule.kt
  core/local/src/main/java/com/terning/core/local/TerningDataStore.kt
  core/local/src/main/java/com/terning/core/local/TerningDataStoreImpl.kt
  data/auth/src/main/java/com/terning/data/auth/dto/request/SignUpRequestDto.kt
  data/auth/src/main/java/com/terning/data/auth/dto/response/SignInResponseDto.kt
  data/auth/src/main/java/com/terning/data/auth/mapper/SignInResponseMapper.kt
  data/auth/src/main/java/com/terning/data/auth/mapper/SignUpRequestMapper.kt
  data/auth/src/main/java/com/terning/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  data/token/build.gradle.kts
  data/token/src/main/java/com/terning/data/token/repositoryimpl/TokenRepositoryImpl.kt
  domain/auth/src/main/java/com/terning/domain/auth/entity/SignInResponse.kt
  domain/auth/src/main/java/com/terning/domain/auth/entity/SignUpRequest.kt
  domain/auth/src/main/java/com/terning/domain/auth/repository/AuthRepository.kt
  domain/token/src/main/java/com/terning/domain/token/repository/TokenRepository.kt
  feature/main/src/main/AndroidManifest.xml
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  gradle/libs.versions.toml
  project.dot.png
Labels: FEAT ✨, 유빈💙

#373 [FEAT/#364] 공고 상세 뷰 / 카카오톡 공유하기
  app/src/main/AndroidManifest.xml
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
  core/designsystem/src/main/java/com/terning/core/designsystem/util/KakaoUtil.kt
  feature/intern/src/main/java/com/terning/feature/intern/InternRoute.kt
  feature/intern/src/main/java/com/terning/feature/intern/InternSideEffect.kt
  feature/intern/src/main/java/com/terning/feature/intern/InternViewModel.kt
  feature/intern/src/main/java/com/terning/feature/intern/InternViewSideEffect.kt
  feature/intern/src/main/res/drawable/ic_intern_share_22.xml
  feature/intern/src/main/res/drawable/ic_share_32.xml
  gradle/libs.versions.toml
Labels: UI 💐, 아린💛

#381 [FEAT/#352] 마이페이지 뷰 / UI 구현, 알림 권한 설정 구현
  app/build.gradle.kts
  core/designsystem/src/main/java/com/terning/core/designsystem/component/dialog/TerningNoticeDialog.kt
  core/firebase/build.gradle.kts
  core/firebase/src/main/java/com/terning/core/firebase/messageservice/TerningMessagingService.kt
  core/local/src/main/java/com/terning/core/local/TerningDataStore.kt
  core/local/src/main/java/com/terning/core/local/TerningDataStoreImpl.kt
  data/user/.gitignore
  data/user/build.gradle.kts
  data/user/src/main/AndroidManifest.xml
  data/user/src/main/java/com/terning/data/user/di/RepositoryModule.kt
  data/user/src/main/java/com/terning/data/user/repositoryimpl/UserRepositoryImpl.kt
  domain/user/.gitignore
  domain/user/build.gradle.kts
  domain/user/src/main/java/com/terning/domain/user/repository/UserRepository.kt
  feature/filtering/build.gradle.kts
  feature/filtering/src/main/java/com/terning/feature/filtering/filteringthree/FilteringThreeViewModel.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/terning/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/terning/feature/home/HomeViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/terning/feature/main/MainActivity.kt
  feature/main/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/MyPageState.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/component/MyPageAlarmDialog.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/component/MyPageItem.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/component/MyPageProfile.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/component/MyPageSection.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/component/MyPageToggleButton.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/model/MyPageUiModel.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditViewModel.kt
  feature/mypage/src/main/res/drawable/ic_my_page_alarm.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/splash/build.gradle.kts
  feature/splash/src/main/java/com/terning/feature/splash/SplashViewModel.kt
  feature/splash/src/main/java/com/terning/feature/splash/component/TerningUpdateDialog.kt
  gradle/libs.versions.toml
  project.dot.png
  settings.gradle.kts
Labels: FEAT ✨, UI 💐, 유빈💙

#383 [FEAT/#382] FCM 푸시알림 커스텀 / Payload 형식에 맞게 구현
  core/designsystem/src/main/java/com/terning/core/designsystem/type/NotificationRedirect.kt
  core/designsystem/src/main/java/com/terning/core/designsystem/util/DeeplinkDefaults.kt
  core/firebase/build.gradle.kts
  core/firebase/src/main/java/com/terning/core/firebase/messageservice/TerningMessagingService.kt
  feature/calendar/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
  feature/calendar/src/main/java/com/terning/feature/calendar/calendar/navigation/CalendarNavigation.kt
  feature/home/src/main/java/com/terning/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/terning/feature/home/navigation/HometNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/terning/feature/main/MainActivity.kt
  feature/main/src/main/java/com/terning/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/terning/feature/main/MainScreen.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditRoute.kt
  feature/search/src/main/java/com/terning/feature/search/search/navigation/SearchNavigation.kt
  feature/splash/src/main/java/com/terning/feature/splash/SplashRoute.kt
  feature/splash/src/main/java/com/terning/feature/splash/navigation/SplashNavigation.kt
Labels: FEAT ✨, 유빈💙

#385 [ADD/#384] 4차 스프린트 / 엠플리튜드 이벤트 추가
  core/analytics/src/main/java/com/terning/core/analytics/EventType.kt
  core/firebase/build.gradle.kts
  core/firebase/src/main/java/com/terning/core/firebase/messageservice/TerningMessagingService.kt
  feature/main/src/main/java/com/terning/feature/main/MainActivity.kt
Labels: ADD ➕, 유빈💙
