Repository teamterning/Terning-Android, pull requests merged in 2025-03, with the labels that each got.

#347 [FEAT/#346] Kotlin 2.0 마이그레이션
  .gitignore
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/terning/build_logic/convention/ComposeAndroid.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: FEAT ✨, 유빈💙

#349 [FEAT/#343] 홈 뷰 / pressed 버튼 추가
  feature/home/src/main/java/com/terning/feature/home/component/HomeFilteringScreen.kt
  feature/home/src/main/java/com/terning/feature/home/component/HomeSortingButton.kt
  feature/home/src/main/java/com/terning/feature/home/component/HomeUpcomingEmptyIntern.kt
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/JobFilteringScreen.kt
Labels: FEAT ✨, UI 💐, 효빈💚

#354 [FEAT/#348] Firebase 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: FEAT ✨, 유빈💙

#353 [FEAT/#351] 테스트 코드 적용
  core/testing/.gitignore
  core/testing/build.gradle.kts
  core/testing/src/main/AndroidManifest.xml
  core/testing/src/main/java/com/terning/testing/util/MainDispatcherRule.kt
  core/testing/src/test/java/com/terning/testing/ExampleUnitTest.kt
  feature/intern/build.gradle.kts
  feature/intern/src/test/java/com/terning/intern/InternViewModelTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEAT ✨, 아린💛

#356 [FIX/#350] 직무 필터링 버튼 기기대응 오류 수정
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/JobFilteringScreen.kt
Labels: FIX 🔨, 효빈💚
