Repository teamterning/Terning-Android, pull requests merged in 2025-01, with the labels that each got.

#316 [CHORE/#310] 빌드로직 구현 수정
  app/build.gradle.kts
  build-logic/src/main/java/com/terning/build_logic/extension/ComposeMetricsExtension.kt
  build-logic/src/main/java/terning.android.data.gradle.kts
  build-logic/src/main/java/terning.android.feature.gradle.kts
  core/designsystem/src/main/res/values/strings.xml
  core/network/build.gradle.kts
  data/auth/build.gradle.kts
  data/calendar/build.gradle.kts
  data/filtering/build.gradle.kts
  data/home/build.gradle.kts
  data/intern/build.gradle.kts
  data/mypage/build.gradle.kts
  data/scrap/build.gradle.kts
  data/search/build.gradle.kts
  data/token/build.gradle.kts
  data/tokenreissue/build.gradle.kts
  feature/calendar/build.gradle.kts
  feature/calendar/src/main/java/com/terning/feature/calendar/list/CalendarListViewModel.kt
  feature/calendar/src/main/java/com/terning/feature/calendar/month/CalendarMonthViewModel.kt
  feature/calendar/src/main/java/com/terning/feature/calendar/week/CalendarWeekViewModel.kt
  feature/calendar/src/main/res/values/strings.xml
  feature/dialog/build.gradle.kts
  feature/dialog/src/main/java/com/terning/feature/dialog/cancel/ScrapCancelViewModel.kt
  feature/dialog/src/main/java/com/terning/feature/dialog/detail/ScrapDialogViewModel.kt
  feature/dialog/src/main/res/values/strings.xml
  feature/filtering/build.gradle.kts
  feature/filtering/src/main/java/com/terning/feature/filtering/filteringthree/FilteringThreeViewModel.kt
  feature/filtering/src/main/res/values/strings.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/terning/feature/home/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
  feature/intern/build.gradle.kts
  feature/main/build.gradle.kts
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/terning/feature/mypage/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditViewModel.kt
  feature/mypage/src/main/res/values/strings.xml
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
  feature/onboarding/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
  feature/onboarding/src/main/res/values/strings.xml
  feature/search/build.gradle.kts
  feature/search/src/main/java/com/terning/feature/search/search/SearchViewModel.kt
  feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/search/src/main/res/values/strings.xml
  gradle.properties
  gradle/libs.versions.toml
Labels: CHORE 🎀, 유빈💙

#317 [FEAT/#315] 딱 맞는 인턴 공고 페이징 구현
  build-logic/src/main/java/terning.kotlin.library.gradle.kts
  data/home/build.gradle.kts
  data/home/src/main/java/com/terning/data/home/datasource/HomeDataSource.kt
  data/home/src/main/java/com/terning/data/home/datasourceimpl/HomeDataSourceImpl.kt
  data/home/src/main/java/com/terning/data/home/dto/response/HomeRecommendInternResponseDto.kt
  data/home/src/main/java/com/terning/data/home/mapper/HomeRecommendInternMapper.kt
  data/home/src/main/java/com/terning/data/home/pagingsource/HomePagingSource.kt
  data/home/src/main/java/com/terning/data/home/repositoryimpl/HomeRepositoryImpl.kt
  data/home/src/main/java/com/terning/data/home/service/HomeService.kt
  domain/home/build.gradle.kts
  domain/home/src/main/java/com/terning/domain/home/entity/HomeRecommendedIntern.kt
  domain/home/src/main/java/com/terning/domain/home/repository/HomeRepository.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/terning/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/terning/feature/home/HomeState.kt
  feature/home/src/main/java/com/terning/feature/home/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: FEAT ✨, UI 💐, 석준💜

#321 [FIX/#319] 필터링 재설정 뷰 / 데이트피커 로직 수정
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/HomeFilteringBottomSheet.kt
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/HomeYearMonthPicker.kt
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/PlanFilteringScreen.kt
Labels: FIX 🔨, 유빈💙

#326 [FIX/#323] 홈, 필터링 재설정 뷰 / 1차 QA 반영
  core/designsystem/src/main/res/values/strings.xml
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/HomeFilteringBottomSheet.kt
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/PlanFilteringScreen.kt
Labels: FIX 🔨, 효빈💚

#327 [FIX/#322] 온보딩, 데이트피커 / 3차 스프린트 QA 반영
  core/designsystem/src/main/java/com/terning/core/designsystem/util/CalendarDefaults.kt
  feature/filtering/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringRoute.kt
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/HomeYearMonthPicker.kt
  feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/PlanFilteringScreen.kt
Labels: FIX 🔨, 유빈💙

#320 [FEAT/#306] 3차 스프린트 탐색 뷰
  data/search/src/main/java/com/terning/data/search/datasource/SearchDataSource.kt
  data/search/src/main/java/com/terning/data/search/datasourceimpl/SearchDataSourceImpl.kt
  data/search/src/main/java/com/terning/data/search/dto/response/SearchBannersResponseDto.kt
  data/search/src/main/java/com/terning/data/search/mapper/SearchBannersMapper.kt
  data/search/src/main/java/com/terning/data/search/repositoryimpl/SearchRepositoryImpl.kt
  data/search/src/main/java/com/terning/data/search/service/SearchService.kt
  domain/search/src/main/java/com/terning/domain/search/entity/SearchBanner.kt
  domain/search/src/main/java/com/terning/domain/search/repository/SearchRepository.kt
  feature/search/src/main/java/com/terning/feature/search/search/SearchRoute.kt
  feature/search/src/main/java/com/terning/feature/search/search/SearchSideEffect.kt
  feature/search/src/main/java/com/terning/feature/search/search/SearchViewModel.kt
  feature/search/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
  feature/search/src/main/java/com/terning/feature/search/search/component/SearchIntern.kt
  feature/search/src/main/java/com/terning/feature/search/search/component/SearchInternList.kt
  feature/search/src/main/java/com/terning/feature/search/search/model/SearchBannerListState.kt
  feature/search/src/main/java/com/terning/feature/search/search/navigation/SearchNavigation.kt
  feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessSideEffect.kt
  feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/search/src/main/java/com/terning/feature/search/searchprocess/navigation/SearchProcessNavigation.kt
Labels: FEAT ✨, 아린💛

#331 [FIX/#330] 달력 영역 수정
  feature/calendar/src/main/java/com/terning/feature/calendar/calendar/component/group/CalendarWeekGroup.kt
Labels: FIX 🔨, 석준💜

#329 [ FEAT/#328] 탐색 뷰 / 페이징 추가
  data/search/build.gradle.kts
  data/search/src/main/java/com/terning/data/search/datasourceimpl/SearchDataSourceImpl.kt
  data/search/src/main/java/com/terning/data/search/dto/request/SearchRequestDto.kt
  data/search/src/main/java/com/terning/data/search/mapper/SearchResultMapper.kt
  data/search/src/main/java/com/terning/data/search/pagingsource/SearchPagingSource.kt
  data/search/src/main/java/com/terning/data/search/repositoryimpl/SearchRepositoryImpl.kt
  domain/search/build.gradle.kts
  domain/search/src/main/java/com/terning/domain/search/entity/SearchResult.kt
  domain/search/src/main/java/com/terning/domain/search/repository/SearchRepository.kt
  feature/search/build.gradle.kts
  feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
  feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
  feature/search/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
  gradle/libs.versions.toml
Labels: FEAT ✨, 아린💛

#335 [CHORE/#334] 버전 업그레이드
  gradle/libs.versions.toml
Labels: CHORE 🎀, 유빈💙
